/** Seed data aligned with semana-ejemplo.md + dashboard-direccion.md + demo canales */

export const USERS = [
  {
    id: "u-mercadeo",
    nombre: "Laura Natalia",
    email: "laura.natalia@unisabana.edu.co",
    rol: "mercadeo" as const,
    activo: 1,
    createdAt: "2026-09-01T08:00:00-05:00",
  },
  {
    id: "u-direccion",
    nombre: "Laura Lucía",
    email: "laura.lucia@unisabana.edu.co",
    rol: "direccion" as const,
    activo: 1,
    createdAt: "2026-09-01T08:00:00-05:00",
  },
];

export const COLEGIOS = [
  {
    id: "c1",
    nombre: "Colegio San Viator",
    ciudadZona: "Usaquén",
    programasFoco: JSON.stringify(["Educación"]),
    contactoPreferido: "email",
    notas: "Bogotá norte",
    ultimoContactoAt: null,
  },
  {
    id: "c2",
    nombre: "Colegio Gimnasio Vermont",
    ciudadZona: "Cajicá",
    programasFoco: JSON.stringify(["Pedagogía"]),
    contactoPreferido: "whatsapp",
    notas: "Follow-up pendiente",
    ultimoContactoAt: "2026-09-08T10:00:00-05:00",
  },
  {
    id: "c3",
    nombre: "Colegio Nueva Granada",
    ciudadZona: "Chía",
    programasFoco: JSON.stringify(["Dirección y Gestión Educativa"]),
    contactoPreferido: "email",
    notas: "Líderes académicos",
    ultimoContactoAt: null,
  },
  {
    id: "c4",
    nombre: "Colegio Los Nogales",
    ciudadZona: "Bogotá norte",
    programasFoco: JSON.stringify(["Dirección y Gestión Educativa"]),
    contactoPreferido: "email",
    notas: "",
    ultimoContactoAt: null,
  },
  {
    id: "c5",
    nombre: "Colegio Marymount",
    ciudadZona: "Bogotá norte",
    programasFoco: JSON.stringify(["Desarrollo Infantil"]),
    contactoPreferido: "whatsapp",
    notas: "Preescolar fuerte",
    ultimoContactoAt: null,
  },
  {
    id: "c6",
    nombre: "Colegio San Jorge de Inglaterra",
    ciudadZona: "Bogotá norte",
    programasFoco: JSON.stringify(["Desarrollo Infantil"]),
    contactoPreferido: "whatsapp",
    notas: "Preescolar fuerte",
    ultimoContactoAt: "2026-09-06T15:00:00-05:00",
  },
  {
    id: "c7",
    nombre: "Colegio Rochester",
    ciudadZona: "Bogotá norte",
    programasFoco: JSON.stringify(["Educación", "Pedagogía"]),
    contactoPreferido: "email",
    notas: "Warm · email abierto",
    ultimoContactoAt: "2026-09-07T11:00:00-05:00",
  },
  {
    id: "c8",
    nombre: "Colegio Tilatá",
    ciudadZona: "La Calera",
    programasFoco: JSON.stringify(["Dirección y Gestión Educativa"]),
    contactoPreferido: "telefono",
    notas: "Corredor oriental",
    ultimoContactoAt: null,
  },
  {
    id: "c9",
    nombre: "IE Normal Superior de Neiva",
    ciudadZona: "Neiva",
    programasFoco: JSON.stringify(["Educación", "Pedagogía"]),
    contactoPreferido: "email",
    notas: "Cohorte regional Huila",
    ultimoContactoAt: "2026-09-05T09:00:00-05:00",
  },
  {
    id: "c10",
    nombre: "Colegio Santa Francisca Romana",
    ciudadZona: "Bogotá norte",
    programasFoco: JSON.stringify(["Desarrollo Infantil"]),
    contactoPreferido: "whatsapp",
    notas: "Preescolar",
    ultimoContactoAt: null,
  },
];

export const LEADS = [
  {
    id: "l1",
    colegioId: "c1",
    nombre: "Rectoría San Viator",
    cargo: "Rectoría",
    email: "rectoria@sanviator.ejemplo.edu.co",
    telefonoWa: null,
    etapaFunnel: "contacto",
    programaInteres: "Maestría en Educación",
    tags: JSON.stringify(["frio", "bogota-norte"]),
    createdAt: "2026-09-08T07:00:00-05:00",
    owner: "Laura Natalia",
    nextTouch: "2026-09-11 · Email follow-up",
    canalOrigen: "email",
    opened: false,
    visitado: false,
    postVisita: null,
  },
  {
    id: "l2",
    colegioId: "c2",
    nombre: "Coordinadora Vermont",
    cargo: "Coordinación académica",
    email: null,
    telefonoWa: "+573001112233",
    etapaFunnel: "interes",
    programaInteres: "Pedagogía",
    tags: JSON.stringify(["warm", "cajica", "caliente"]),
    createdAt: "2026-09-08T07:00:00-05:00",
    owner: "Laura Natalia",
    nextTouch: "2026-09-10 · WA + llamada 90 s",
    canalOrigen: "whatsapp",
    opened: true,
    visitado: false,
    postVisita: null,
  },
  {
    id: "l3",
    colegioId: "c3",
    nombre: "Dirección Nueva Granada",
    cargo: "Dirección",
    email: "direccion@nuevagranada.ejemplo.edu.co",
    telefonoWa: null,
    etapaFunnel: "agendada",
    programaInteres: "Dirección y Gestión Educativa",
    tags: JSON.stringify(["lideres", "chia"]),
    createdAt: "2026-09-08T07:00:00-05:00",
    owner: "Laura Natalia",
    nextTouch: "2026-09-20 · Visita campus Chía",
    canalOrigen: "email",
    opened: true,
    visitado: false,
    postVisita: null,
  },
  {
    id: "l4",
    colegioId: "c5",
    nombre: "Coordinación preescolar Marymount",
    cargo: "Coordinación preescolar",
    email: null,
    telefonoWa: "+573004445566",
    etapaFunnel: "post-visita",
    programaInteres: "Desarrollo Infantil",
    tags: JSON.stringify(["preescolar", "post-visita"]),
    createdAt: "2026-09-01T07:00:00-05:00",
    owner: "Laura Natalia",
    nextTouch: "2026-09-11 · Reminder D+3 docs",
    canalOrigen: "visita",
    opened: true,
    visitado: true,
    postVisita: {
      docs: false,
      pago: false,
      beca: true,
      reminderD1: true,
      reminderD3: false,
      visitaAt: "2026-09-08T09:00:00-05:00",
      notas: "Visitó sáb 8 sep · pendiente carpeta y pago inscripción",
    },
  },
  {
    id: "l5",
    colegioId: "c6",
    nombre: "Coordinación preescolar San Jorge",
    cargo: "Coordinación preescolar",
    email: "preescolar@sanjorge.ejemplo.edu.co",
    telefonoWa: "+573007778899",
    etapaFunnel: "post-visita",
    programaInteres: "Desarrollo Infantil",
    tags: JSON.stringify(["preescolar", "post-visita"]),
    createdAt: "2026-09-02T07:00:00-05:00",
    owner: "Laura Natalia",
    nextTouch: "2026-09-10 · Reminder D+1 pago",
    canalOrigen: "visita",
    opened: true,
    visitado: true,
    postVisita: {
      docs: true,
      pago: false,
      beca: false,
      reminderD1: false,
      reminderD3: false,
      visitaAt: "2026-09-09T09:00:00-05:00",
      notas: "Visitó mar 9 sep · docs OK · falta pago y decisión beca",
    },
  },
  {
    id: "l6",
    colegioId: "c4",
    nombre: "Rectoría Los Nogales",
    cargo: "Rectoría",
    email: "rectoria@losnogales.ejemplo.edu.co",
    telefonoWa: null,
    etapaFunnel: "interes",
    programaInteres: "Dirección y Gestión Educativa",
    tags: JSON.stringify(["lideres", "bogota-norte"]),
    createdAt: "2026-09-06T07:00:00-05:00",
    owner: "Laura Natalia",
    nextTouch: "2026-09-12 · Invitar visita",
    canalOrigen: "linkedin",
    opened: true,
    visitado: false,
    postVisita: null,
  },
  {
    id: "l7",
    colegioId: "c7",
    nombre: "Coordinación académica Rochester",
    cargo: "Coordinación académica",
    email: "academica@rochester.ejemplo.edu.co",
    telefonoWa: "+573002223344",
    etapaFunnel: "interes",
    programaInteres: "Maestría en Educación",
    tags: JSON.stringify(["warm", "opened"]),
    createdAt: "2026-09-07T07:00:00-05:00",
    owner: "Laura Natalia",
    nextTouch: "2026-09-11 · Llamada 90 s",
    canalOrigen: "email",
    opened: true,
    visitado: false,
    postVisita: null,
  },
  {
    id: "l8",
    colegioId: "c8",
    nombre: "Dirección Tilatá",
    cargo: "Dirección",
    email: "direccion@tilata.ejemplo.edu.co",
    telefonoWa: null,
    etapaFunnel: "contacto",
    programaInteres: "Dirección y Gestión Educativa",
    tags: JSON.stringify(["frio", "calera"]),
    createdAt: "2026-09-08T07:00:00-05:00",
    owner: "Laura Natalia",
    nextTouch: "2026-09-15 · Email frío",
    canalOrigen: "email",
    opened: false,
    visitado: false,
    postVisita: null,
  },
  {
    id: "l9",
    colegioId: "c9",
    nombre: "Rectoría Normal Superior Neiva",
    cargo: "Rectoría",
    email: "rectoria@normalneiva.ejemplo.edu.co",
    telefonoWa: "+57871112233",
    etapaFunnel: "interes",
    programaInteres: "Maestría en Educación",
    tags: JSON.stringify(["regional", "neiva", "tibio"]),
    createdAt: "2026-09-05T07:00:00-05:00",
    owner: "Laura Natalia",
    nextTouch: "2026-09-12 · Convenio / cohorte Neiva",
    canalOrigen: "region",
    opened: true,
    visitado: false,
    postVisita: null,
  },
  {
    id: "l10",
    colegioId: "c10",
    nombre: "Coordinación preescolar Santa Francisca",
    cargo: "Coordinación preescolar",
    email: null,
    telefonoWa: "+573005556677",
    etapaFunnel: "contacto",
    programaInteres: "Desarrollo Infantil",
    tags: JSON.stringify(["preescolar", "frio"]),
    createdAt: "2026-09-09T07:00:00-05:00",
    owner: "Laura Natalia",
    nextTouch: "2026-09-13 · WA primer contacto",
    canalOrigen: "whatsapp",
    opened: false,
    visitado: false,
    postVisita: null,
  },
  {
    id: "l11",
    colegioId: "c3",
    nombre: "Coordinación académica Nueva Granada",
    cargo: "Coordinación académica",
    email: "coord@nuevagranada.ejemplo.edu.co",
    telefonoWa: "+573009998877",
    etapaFunnel: "visita",
    programaInteres: "Pedagogía",
    tags: JSON.stringify(["chia", "visita"]),
    createdAt: "2026-09-04T07:00:00-05:00",
    owner: "Laura Natalia",
    nextTouch: "2026-09-20 · Confirmación show-up",
    canalOrigen: "email",
    opened: true,
    visitado: false,
    postVisita: null,
  },
  {
    id: "l12",
    colegioId: "c2",
    nombre: "Rectoría Gimnasio Vermont",
    cargo: "Rectoría",
    email: "rectoria@vermont.ejemplo.edu.co",
    telefonoWa: null,
    etapaFunnel: "aplicacion",
    programaInteres: "Pedagogía",
    tags: JSON.stringify(["caliente", "cajica", "app"]),
    createdAt: "2026-08-28T07:00:00-05:00",
    owner: "Laura Natalia",
    nextTouch: "2026-09-11 · Empujar matrícula / early bird",
    canalOrigen: "visita",
    opened: true,
    visitado: true,
    postVisita: null,
  },
];

/** Hoy seed: email, whatsapp, llamada, linkedin_borrador, visita, region/convenio */
export const TAREAS = [
  {
    id: "t1",
    fecha: "2026-09-10",
    orden: 1,
    tipo: "email_frio",
    canal: "email",
    titulo: "Email frío — colegios Bogotá norte",
    programaFoco: "Maestría en Educación",
    dest: "Rectoría / Coordinación — Colegio San Viator (Usaquén)",
    asunto:
      "Invitación a conocer la Maestría en Educación · Universidad de La Sabana",
    cuerpo:
      "Estimada/o [Nombre / Rectoría],\n\nSoy del equipo de marketing de la Facultad de Educación de la Universidad de La Sabana. Escribimos para compartir una oportunidad de formación avanzada pensada para docentes y líderes de colegios como el suyo en el norte de Bogotá.\n\n• Visitas de campus: sábados [CONFIRMAR: 20 y 27 sep 2026], 9:00–11:00\n• Descuento early bird antes de [CONFIRMAR: 15 oct 2026]: [CONFIRMAR: 15%]\n• Inversión referencial cohorte 2027-1: [CONFIRMAR: $28.500.000]\n\n¿Le parece bien si agendamos 15 minutos esta semana?\n\nFacultad de Educación · Universidad de La Sabana",
    estado: "pendiente",
    creadoPorAgente: "Agente Captación",
    aprobadaPorUserId: null,
    enviadaAt: null,
    acciones: JSON.stringify(["aprobar", "editar", "enviar"]),
  },
  {
    id: "t2",
    fecha: "2026-09-10",
    orden: 2,
    tipo: "wa_followup",
    canal: "whatsapp",
    titulo: "WhatsApp — follow-up colegio Cajicá",
    programaFoco: "Pedagogía",
    dest: "Coordinadora académica — Colegio Gimnasio Vermont (Cajicá)",
    asunto: "",
    cuerpo:
      "Hola [Nombre], buen día 👋\n\nSoy del equipo de la Facultad de Educación de La Sabana. El martes le escribimos sobre la Maestría en Pedagogía y queríamos retomar:\n\n📅 Visita campus Chía: sábado [CONFIRMAR: 20 sep], 9:00–11:00\n🎓 Programas: Educación, Pedagogía, Dirección y Gestión, Desarrollo Infantil\n💰 Early bird hasta [CONFIRMAR: 15 oct]: [CONFIRMAR: 15%]\n\n¿Le agendo la visita o le llamo 90 segundos?\n\n— Facultad de Educación · Unisabana",
    estado: "pendiente",
    creadoPorAgente: "Agente Captación",
    aprobadaPorUserId: null,
    enviadaAt: null,
    acciones: JSON.stringify(["aprobar", "editar", "enviar"]),
  },
  {
    id: "t3",
    fecha: "2026-09-10",
    orden: 3,
    tipo: "llamada",
    canal: "telefono",
    titulo: "Llamada IA — warm lead Vermont (piloto)",
    programaFoco: "Pedagogía",
    dest: "Coordinadora académica — Colegio Gimnasio Vermont",
    asunto: "",
    cuerpo:
      "[0:00–0:15] Hola, ¿hablo con [Nombre]? Soy del equipo de la Facultad de Educación de La Sabana. ¿Le tomo 90 segundos?\n\n[0:15–0:35] Retomamos la Maestría en Pedagogía (cohorte 2027-1) y la visita campus Chía.\n\n[0:35–0:55] Dos caminos: (1) visita [CONFIRMAR: sáb 20 o 27 sep] 9:00–11:00, o (2) brochure por WhatsApp. Early bird [CONFIRMAR: 15%] hasta [CONFIRMAR: 15 oct].\n\n[0:55–1:15] ¿Le agendo la visita, le marco un callback, o le dejo el PDF?\n\n— Guion piloto Llamada IA · DEMO sin telefonía real",
    estado: "pendiente",
    creadoPorAgente: "Agente Captación",
    aprobadaPorUserId: null,
    enviadaAt: null,
    acciones: JSON.stringify(["aprobar", "editar", "enviar", "simular_llamada"]),
  },
  {
    id: "t4",
    fecha: "2026-09-10",
    orden: 4,
    tipo: "linkedin_borrador",
    canal: "linkedin",
    titulo: "LinkedIn — borrador conexión / InMail a rectores",
    programaFoco: "Maestría en Educación",
    dest: "Rectoría — Colegio San Viator / Nueva Granada / Marymount",
    asunto: "Borrador LinkedIn (sin auto-envío)",
    cuerpo:
      "Estimada/o Rector/a,\n\nSoy del equipo de la Facultad de Educación de la Universidad de La Sabana. Me gustaría conectar para compartir la Maestría en Educación (cohorte 2027-1) y las visitas de campus los sábados [CONFIRMAR: 20 y 27 sep].\n\nEarly bird [CONFIRMAR: 15%] hasta [CONFIRMAR: 15 oct] · Inversión referencial [CONFIRMAR: $28.500.000].\n\n¿Le parece bien una nota breve o una visita de 2 h en Chía?\n\n— Facultad de Educación · Unisabana\n\n⚠️ LinkedIn: solo borradores. No hay envío automático — copiar/pegar tras aprobar.",
    estado: "pendiente",
    creadoPorAgente: "Agente Captación",
    aprobadaPorUserId: null,
    enviadaAt: null,
    acciones: JSON.stringify(["aprobar", "editar"]),
  },
  {
    id: "t5",
    fecha: "2026-09-10",
    orden: 5,
    tipo: "invitacion_visita",
    canal: "visita",
    titulo: "Reunión / visita campus — Agendar en Outlook",
    programaFoco: "Todos (4 maestrías)",
    dest: "Dirección Nueva Granada · direccion@nuevagranada.ejemplo.edu.co",
    asunto:
      "Invitación — Visita campus Chía · Maestrías Facultad de Educación",
    cuerpo:
      "Estimada/o [Nombre],\n\nLo/la esperamos en el campus Unisabana (Chía) para una visita de 2 horas.\n\n📍 Campus Unisabana, Chía\n🗓️ Próximos cupos abiertos:\n   · [CONFIRMAR: sábado 20 de septiembre de 2026] · 9:00–11:00\n   · [CONFIRMAR: sábado 27 de septiembre de 2026] · 9:00–11:00\n   · [CONFIRMAR: sábado 4 de octubre de 2026] · 9:00–11:00\n\nAGENDA\n09:00–09:20  Bienvenida\n09:20–09:50  Programas\n09:50–10:20  Admisiones y early bird [CONFIRMAR: 15% hasta 15 oct]\n10:20–10:45  Recorrido campus\n10:45–11:00  Preguntas e inscripción\n\nInversión referencial: [CONFIRMAR: $28.5M–$29.2M].",
    estado: "pendiente",
    creadoPorAgente: "Agente Admisiones",
    aprobadaPorUserId: null,
    enviadaAt: null,
    acciones: JSON.stringify(["aprobar", "editar", "agendar"]),
  },
  {
    id: "t6",
    fecha: "2026-09-10",
    orden: 6,
    tipo: "email_segmento",
    canal: "email",
    titulo: "Email — líderes académicos Chía / Cajicá",
    programaFoco: "Dirección y Gestión Educativa",
    dest: "Dirección — Colegio Nueva Granada / Los Nogales",
    asunto:
      "Para quienes lideran colegios: Maestría en Dirección y Gestión Educativa",
    cuerpo:
      "Estimada/o [Nombre],\n\nLos colegios del corredor Chía–Cajicá–Bogotá norte enfrentan retos de liderazgo y gestión de equipos. La Maestría en Dirección y Gestión Educativa de La Sabana está pensada para ese perfil.\n\nFecha sugerida de visita: [CONFIRMAR: sábado 27 sep 2026], 9:00–11:00.\nInversión referencial: [CONFIRMAR: $29.200.000] · Early bird [CONFIRMAR: 15%] hasta [CONFIRMAR: 15 oct 2026].\n\nSi prefiere una llamada de 90 segundos primero, responda con un horario.\n\nFacultad de Educación · Universidad de La Sabana",
    estado: "pendiente",
    creadoPorAgente: "Agente Inteligencia",
    aprobadaPorUserId: null,
    enviadaAt: null,
    acciones: JSON.stringify(["aprobar", "editar", "enviar"]),
  },
  {
    id: "t7",
    fecha: "2026-09-10",
    orden: 7,
    tipo: "secuencia_d",
    canal: "whatsapp",
    titulo: "Secuencia follow-up D+3 / D+7 / D+14",
    programaFoco: "Según lead",
    dest: "Leads sin avance post-contacto o visita",
    asunto: "",
    cuerpo:
      "D+3: seguimiento amable + oferta visita [CONFIRMAR: 20 o 27 sep].\nD+7: cupos visita + early bird cierra [CONFIRMAR: 15 oct] + PDF programa.\nD+14: último toque; opción recontacto noviembre.\n\nUn solo «Aprobar» programa los tres toques.",
    estado: "pendiente",
    creadoPorAgente: "Agente Orquestadora",
    aprobadaPorUserId: null,
    enviadaAt: null,
    acciones: JSON.stringify(["aprobar", "editar", "enviar"]),
  },
  {
    id: "t8",
    fecha: "2026-09-10",
    orden: 8,
    tipo: "wa_programa",
    canal: "whatsapp",
    titulo: "WhatsApp — Desarrollo Infantil (preescolar fuerte)",
    programaFoco: "Desarrollo Infantil",
    dest: "Coordinación preescolar — Marymount / San Jorge de Inglaterra",
    asunto: "",
    cuerpo:
      "Hola [Nombre] 👋\n\nEquipo Facultad de Educación · Universidad de La Sabana.\n\nVimos que en [Colegio] el área de primera infancia es muy fuerte. Queríamos compartir la Maestría en Desarrollo Infantil (cohorte 2027-1).\n\n• Visita campus Chía — [CONFIRMAR: sáb 20 o 27 sep], 9:00–11:00\n• Early bird [CONFIRMAR: 15%] hasta [CONFIRMAR: 15 oct]\n• Inversión [CONFIRMAR: $28.800.000]\n\nResponda VISITA, LLAMADA o PDF.",
    estado: "pendiente",
    creadoPorAgente: "Agente Captación",
    aprobadaPorUserId: null,
    enviadaAt: null,
    acciones: JSON.stringify(["aprobar", "editar", "enviar", "agendar"]),
  },
  {
    id: "t9",
    fecha: "2026-09-10",
    orden: 9,
    tipo: "carta_secretaria",
    canal: "region",
    titulo: "Región — carta a Secretaría de Educación (convenio)",
    programaFoco: "Cohortes regionales · 4 maestrías",
    dest: "Secretaría de Educación · [CONFIRMAR: municipio / departamento]",
    asunto:
      "Convenio territorial · Maestrías Facultad de Educación · Unisabana",
    cuerpo:
      "Estimada/o Secretaria/o [Nombre],\n\nDesde la Facultad de Educación de la Universidad de La Sabana queremos proponer un convenio territorial para que docentes de su jurisdicción cursen maestrías (Educación, Pedagogía, Dirección y Gestión, Desarrollo Infantil) con apoyo de la entidad territorial.\n\n• Cohortes regionales 2027-1 — fechas [CONFIRMAR]\n• Cupos preferentes para docentes de planta y provisionales\n• Early bird institucional [CONFIRMAR: 15%] hasta [CONFIRMAR: 15 oct 2026]\n• Inversión referencial [CONFIRMAR: $28.5M–$29.2M] · pago entidad [CONFIRMAR]\n\nAgenda sugerida: reunión 30 min o visita campus Chía [CONFIRMAR: sáb 20 o 27 sep].\n\nFacultad de Educación · Universidad de La Sabana\nAgente Región · convenios territoriales",
    estado: "pendiente",
    creadoPorAgente: "Agente Región",
    aprobadaPorUserId: null,
    enviadaAt: null,
    acciones: JSON.stringify(["aprobar", "editar", "enviar"]),
  },
];

export const ACTIVIDAD_SEED = [
  {
    id: "a1",
    time: "07:12",
    actor: "Agente Captación",
    text: "Preparó tarea #1 · Email frío San Viator (Usaquén).",
    kind: "agente",
    createdAt: "2026-09-10T07:12:00-05:00",
  },
  {
    id: "a2",
    time: "07:14",
    actor: "Agente Captación",
    text: "Preparó tarea #2 · WA follow-up Gimnasio Vermont.",
    kind: "agente",
    createdAt: "2026-09-10T07:14:00-05:00",
  },
  {
    id: "a3",
    time: "07:16",
    actor: "Agente Captación",
    text: "Preparó tarea #3 · Guion Llamada IA (piloto) Vermont.",
    kind: "agente",
    createdAt: "2026-09-10T07:16:00-05:00",
  },
  {
    id: "a4",
    time: "07:18",
    actor: "Agente Captación",
    text: "Preparó tarea #4 · 3 borradores LinkedIn a rectores.",
    kind: "agente",
    createdAt: "2026-09-10T07:18:00-05:00",
  },
  {
    id: "a5",
    time: "07:22",
    actor: "Agente Admisiones",
    text: "Armó agenda 2 h Chía + cupos sábados [CONFIRMAR] · tarea #5.",
    kind: "agente",
    createdAt: "2026-09-10T07:22:00-05:00",
  },
  {
    id: "a6",
    time: "07:25",
    actor: "Agente Inteligencia",
    text: "Segmentó líderes Chía/Cajicá · tarea #6 email Dirección y Gestión.",
    kind: "agente",
    createdAt: "2026-09-10T07:25:00-05:00",
  },
  {
    id: "a7",
    time: "07:28",
    actor: "Agente Orquestadora",
    text: "Programó borrador D+3/D+7/D+14 para 18 leads fríos.",
    kind: "agente",
    createdAt: "2026-09-10T07:28:00-05:00",
  },
  {
    id: "a8",
    time: "07:30",
    actor: "Agente Región",
    text: "Preparó tarea #9 · carta convenio a Secretaría de Educación.",
    kind: "agente",
    createdAt: "2026-09-10T07:30:00-05:00",
  },
];

export const METRICA = {
  fecha: "2026-09-10",
  colegiosContactados: 86,
  respuestas: 126,
  visitasAgendadas: 48,
  visitasRealizadas: 36,
  inscritos: 14,
  matriculas: 6,
  ingresoProyectadoCop: 165000000,
  notasAgente:
    "Embudo EJEMPLO 420→6 · meta 40 · gap ~$550–605M · semáforo amarillo",
};

export const FUNNEL_EJEMPLO = [
  { etapa: "Contactos", valor: 420, conv: null as string | null },
  { etapa: "Interés", valor: 126, conv: "30%" },
  { etapa: "Agendadas", valor: 48, conv: "38%" },
  { etapa: "Visitaron", valor: 36, conv: "75%" },
  { etapa: "Apps iniciadas", valor: 22, conv: "61%" },
  { etapa: "Apps enviadas", valor: 14, conv: "64%" },
  { etapa: "Matrículas", valor: 6, conv: "meta 40" },
];
