/** Seed data aligned with semana-ejemplo.md + dashboard-direccion.md */

export const USERS = [
  {
    id: "u-mercadeo",
    nombre: "Ana Mercadeo",
    email: "ana.mercadeo@unisabana.edu.co",
    rol: "mercadeo" as const,
    activo: 1,
    createdAt: "2026-09-01T08:00:00-05:00",
  },
  {
    id: "u-direccion",
    nombre: "Dirección Facultad",
    email: "direccion.educacion@unisabana.edu.co",
    rol: "direccion" as const,
    activo: 1,
    createdAt: "2026-09-01T08:00:00-05:00",
  },
];

export const COLEGIOS = [
  {
    id: "c1",
    nombre: "Colegio San Viator",
    ciudadZona: "Usaquén",
    programasFoco: JSON.stringify(["Educación"]),
    contactoPreferido: "email",
    notas: "Bogotá norte",
    ultimoContactoAt: null,
  },
  {
    id: "c2",
    nombre: "Colegio Gimnasio Vermont",
    ciudadZona: "Cajicá",
    programasFoco: JSON.stringify(["Pedagogía"]),
    contactoPreferido: "whatsapp",
    notas: "Follow-up pendiente",
    ultimoContactoAt: "2026-09-08T10:00:00-05:00",
  },
  {
    id: "c3",
    nombre: "Colegio Nueva Granada",
    ciudadZona: "Chía",
    programasFoco: JSON.stringify(["Dirección y Gestión Educativa"]),
    contactoPreferido: "email",
    notas: "Líderes académicos",
    ultimoContactoAt: null,
  },
  {
    id: "c4",
    nombre: "Colegio Los Nogales",
    ciudadZona: "Bogotá norte",
    programasFoco: JSON.stringify(["Dirección y Gestión Educativa"]),
    contactoPreferido: "email",
    notas: "",
    ultimoContactoAt: null,
  },
  {
    id: "c5",
    nombre: "Colegio Marymount",
    ciudadZona: "Bogotá norte",
    programasFoco: JSON.stringify(["Desarrollo Infantil"]),
    contactoPreferido: "whatsapp",
    notas: "Preescolar fuerte",
    ultimoContactoAt: null,
  },
  {
    id: "c6",
    nombre: "Colegio San Jorge de Inglaterra",
    ciudadZona: "Bogotá norte",
    programasFoco: JSON.stringify(["Desarrollo Infantil"]),
    contactoPreferido: "whatsapp",
    notas: "Preescolar fuerte",
    ultimoContactoAt: null,
  },
];

export const LEADS = [
  {
    id: "l1",
    colegioId: "c1",
    nombre: "Rectoría San Viator",
    cargo: "Rectoría / Coordinación",
    email: "rectoria@sanviator.ejemplo.edu.co",
    telefonoWa: null,
    etapaFunnel: "contacto",
    programaInteres: "Maestría en Educación",
    tags: JSON.stringify(["frio", "bogota-norte"]),
    createdAt: "2026-09-08T07:00:00-05:00",
  },
  {
    id: "l2",
    colegioId: "c2",
    nombre: "Coordinadora Vermont",
    cargo: "Coordinación académica",
    email: null,
    telefonoWa: "+573001112233",
    etapaFunnel: "interes",
    programaInteres: "Pedagogía",
    tags: JSON.stringify(["warm", "cajica"]),
    createdAt: "2026-09-08T07:00:00-05:00",
  },
  {
    id: "l3",
    colegioId: "c3",
    nombre: "Dirección Nueva Granada",
    cargo: "Dirección",
    email: "direccion@nuevagranada.ejemplo.edu.co",
    telefonoWa: null,
    etapaFunnel: "contacto",
    programaInteres: "Dirección y Gestión Educativa",
    tags: JSON.stringify(["lideres"]),
    createdAt: "2026-09-08T07:00:00-05:00",
  },
  {
    id: "l4",
    colegioId: "c5",
    nombre: "Coordinación preescolar Marymount",
    cargo: "Coordinación preescolar",
    email: null,
    telefonoWa: "+573004445566",
    etapaFunnel: "contacto",
    programaInteres: "Desarrollo Infantil",
    tags: JSON.stringify(["preescolar"]),
    createdAt: "2026-09-08T07:00:00-05:00",
  },
];

export const TAREAS = [
  {
    id: "t1",
    fecha: "2026-09-10",
    orden: 1,
    tipo: "email_frio",
    canal: "email",
    titulo: "Email frío — colegios Bogotá norte",
    programaFoco: "Maestría en Educación",
    dest: "Rectoría / Coordinación — Colegio San Viator (Usaquén)",
    asunto:
      "Invitación a conocer la Maestría en Educación · Universidad de La Sabana",
    cuerpo:
      "Estimada/o [Nombre / Rectoría],\n\nSoy del equipo de marketing de la Facultad de Educación de la Universidad de La Sabana. Escribimos para compartir una oportunidad de formación avanzada pensada para docentes y líderes de colegios como el suyo en el norte de Bogotá.\n\n• Visitas de campus: sábados [CONFIRMAR: 20 y 27 sep 2026], 9:00–11:00\n• Descuento early bird antes de [CONFIRMAR: 15 oct 2026]: [CONFIRMAR: 15%]\n• Inversión referencial cohorte 2027-1: [CONFIRMAR: $28.500.000]\n\n¿Le parece bien si agendamos 15 minutos esta semana?\n\nFacultad de Educación · Universidad de La Sabana",
    estado: "pendiente",
    creadoPorAgente: "Agente Outreach",
    aprobadaPorUserId: null,
    enviadaAt: null,
    acciones: JSON.stringify(["aprobar", "editar", "enviar"]),
  },
  {
    id: "t2",
    fecha: "2026-09-10",
    orden: 2,
    tipo: "wa_followup",
    canal: "whatsapp",
    titulo: "WhatsApp — follow-up colegio Cajicá",
    programaFoco: "Pedagogía",
    dest: "Coordinadora académica — Colegio Gimnasio Vermont (Cajicá)",
    asunto: "",
    cuerpo:
      "Hola [Nombre], buen día 👋\n\nSoy del equipo de la Facultad de Educación de La Sabana. El martes le escribimos sobre la Maestría en Pedagogía y queríamos retomar:\n\n📅 Visita campus Chía: sábado [CONFIRMAR: 20 sep], 9:00–11:00\n🎓 Programas: Educación, Pedagogía, Dirección y Gestión, Desarrollo Infantil\n💰 Early bird hasta [CONFIRMAR: 15 oct]: [CONFIRMAR: 15%]\n\n¿Le agendo la visita o le llamo 90 segundos?\n\n— Facultad de Educación · Unisabana",
    estado: "pendiente",
    creadoPorAgente: "Agente Follow-up",
    aprobadaPorUserId: null,
    enviadaAt: null,
    acciones: JSON.stringify(["aprobar", "editar", "enviar"]),
  },
  {
    id: "t3",
    fecha: "2026-09-10",
    orden: 3,
    tipo: "email_segmento",
    canal: "email",
    titulo: "Email — líderes académicos Chía / Cajicá",
    programaFoco: "Dirección y Gestión Educativa",
    dest: "Dirección — Colegio Nueva Granada / Los Nogales",
    asunto:
      "Para quienes lideran colegios: Maestría en Dirección y Gestión Educativa",
    cuerpo:
      "Estimada/o [Nombre],\n\nLos colegios del corredor Chía–Cajicá–Bogotá norte enfrentan retos de liderazgo y gestión de equipos. La Maestría en Dirección y Gestión Educativa de La Sabana está pensada para ese perfil.\n\nFecha sugerida de visita: [CONFIRMAR: sábado 27 sep 2026], 9:00–11:00.\nInversión referencial: [CONFIRMAR: $29.200.000] · Early bird [CONFIRMAR: 15%] hasta [CONFIRMAR: 15 oct 2026].\n\nSi prefiere una llamada de 90 segundos primero, responda con un horario.\n\nFacultad de Educación · Universidad de La Sabana",
    estado: "pendiente",
    creadoPorAgente: "Agente Segmentación",
    aprobadaPorUserId: null,
    enviadaAt: null,
    acciones: JSON.stringify(["aprobar", "editar", "enviar"]),
  },
  {
    id: "t4",
    fecha: "2026-09-10",
    orden: 4,
    tipo: "guion_llamada",
    canal: "telefono",
    titulo: "Guion de llamada — 90 segundos",
    programaFoco: "Cualquiera (adaptar)",
    dest: "Warm lead de colegio — primer contacto",
    asunto: "",
    cuerpo:
      "[0:00–0:15] Hola, ¿hablo con [Nombre]? Soy [Tu nombre] de la Facultad de Educación de la Universidad de La Sabana. ¿Le tomo 90 segundos?\n\n[0:15–0:35] Estamos abriendo la cohorte 2027-1: Educación, Pedagogía, Dirección y Gestión, y Desarrollo Infantil.\n\n[0:35–0:55] Dos caminos: (1) visita campus Chía [CONFIRMAR: sáb 20 o 27 sep], o (2) brochure por WhatsApp. Early bird [CONFIRMAR: 15%] hasta [CONFIRMAR: 15 oct].\n\n[0:55–1:15] ¿Le agendo la visita o le mando la info por WhatsApp ahora?",
    estado: "pendiente",
    creadoPorAgente: "Agente Scripts",
    aprobadaPorUserId: null,
    enviadaAt: null,
    acciones: JSON.stringify(["aprobar", "editar", "enviar"]),
  },
  {
    id: "t5",
    fecha: "2026-09-10",
    orden: 5,
    tipo: "invitacion_visita",
    canal: "email",
    titulo: "Invitación visita campus Chía — 2 horas",
    programaFoco: "Todos (4 maestrías)",
    dest: "Lista visitas confirmables",
    asunto:
      "Invitación — Visita campus Chía · Maestrías Facultad de Educación",
    cuerpo:
      "Estimada/o [Nombre],\n\nLo/la esperamos en el campus Unisabana (Chía) para una visita de 2 horas.\n\n📍 Campus Unisabana, Chía\n🗓️ [CONFIRMAR: sábado 20 de septiembre de 2026]\n🕘 9:00 – 11:00\n\nAGENDA\n09:00–09:20  Bienvenida\n09:20–09:50  Programas\n09:50–10:20  Admisiones y early bird [CONFIRMAR: 15% hasta 15 oct]\n10:20–10:45  Recorrido campus\n10:45–11:00  Preguntas e inscripción\n\nInversión referencial: [CONFIRMAR: $28.5M–$29.2M].",
    estado: "pendiente",
    creadoPorAgente: "Agente Visitas",
    aprobadaPorUserId: null,
    enviadaAt: null,
    acciones: JSON.stringify(["aprobar", "editar", "agendar", "enviar"]),
  },
  {
    id: "t6",
    fecha: "2026-09-10",
    orden: 6,
    tipo: "secuencia_d",
    canal: "whatsapp",
    titulo: "Secuencia follow-up D+3 / D+7 / D+14",
    programaFoco: "Según lead",
    dest: "Leads sin avance post-contacto o visita",
    asunto: "",
    cuerpo:
      "D+3: seguimiento amable + oferta visita [CONFIRMAR: 20 o 27 sep].\nD+7: cupos visita + early bird cierra [CONFIRMAR: 15 oct] + PDF programa.\nD+14: último toque; opción recontacto noviembre.\n\nUn solo «Aprobar» programa los tres toques.",
    estado: "pendiente",
    creadoPorAgente: "Agente Secuencias",
    aprobadaPorUserId: null,
    enviadaAt: null,
    acciones: JSON.stringify(["aprobar", "editar", "enviar"]),
  },
  {
    id: "t7",
    fecha: "2026-09-10",
    orden: 7,
    tipo: "wa_programa",
    canal: "whatsapp",
    titulo: "WhatsApp — Desarrollo Infantil (preescolar fuerte)",
    programaFoco: "Desarrollo Infantil",
    dest: "Coordinación preescolar — Marymount / San Jorge de Inglaterra",
    asunto: "",
    cuerpo:
      "Hola [Nombre] 👋\n\nEquipo Facultad de Educación · Universidad de La Sabana.\n\nVimos que en [Colegio] el área de primera infancia es muy fuerte. Queríamos compartir la Maestría en Desarrollo Infantil (cohorte 2027-1).\n\n• Visita campus Chía — [CONFIRMAR: sáb 20 o 27 sep], 9:00–11:00\n• Early bird [CONFIRMAR: 15%] hasta [CONFIRMAR: 15 oct]\n• Inversión [CONFIRMAR: $28.800.000]\n\nResponda VISITA, LLAMADA o PDF.",
    estado: "pendiente",
    creadoPorAgente: "Agente Segmentación",
    aprobadaPorUserId: null,
    enviadaAt: null,
    acciones: JSON.stringify(["aprobar", "editar", "enviar", "agendar"]),
  },
];

export const ACTIVIDAD_SEED = [
  {
    id: "a1",
    time: "07:12",
    actor: "Agente Outreach",
    text: "Preparó tarea #1 · Email frío San Viator (Usaquén).",
    kind: "agente",
    createdAt: "2026-09-10T07:12:00-05:00",
  },
  {
    id: "a2",
    time: "07:14",
    actor: "Agente Follow-up",
    text: "Preparó tarea #2 · WA follow-up Gimnasio Vermont.",
    kind: "agente",
    createdAt: "2026-09-10T07:14:00-05:00",
  },
  {
    id: "a3",
    time: "07:18",
    actor: "Agente Segmentación",
    text: "Preparó tareas #3 y #7 · líderes Chía y Desarrollo Infantil.",
    kind: "agente",
    createdAt: "2026-09-10T07:18:00-05:00",
  },
  {
    id: "a4",
    time: "07:22",
    actor: "Agente Visitas",
    text: "Armó agenda 2 h Chía + tarea #5 invitaciones.",
    kind: "agente",
    createdAt: "2026-09-10T07:22:00-05:00",
  },
  {
    id: "a5",
    time: "07:25",
    actor: "Agente Secuencias",
    text: "Programó borrador D+3/D+7/D+14 para 18 leads fríos.",
    kind: "agente",
    createdAt: "2026-09-10T07:25:00-05:00",
  },
  {
    id: "a6",
    time: "07:28",
    actor: "Agente Scripts",
    text: "Actualizó guion 90 s con early bird [CONFIRMAR].",
    kind: "agente",
    createdAt: "2026-09-10T07:28:00-05:00",
  },
];

export const METRICA = {
  fecha: "2026-09-10",
  colegiosContactados: 86,
  respuestas: 126,
  visitasAgendadas: 48,
  visitasRealizadas: 36,
  inscritos: 14,
  matriculas: 6,
  ingresoProyectadoCop: 165000000,
  notasAgente:
    "Embudo EJEMPLO 420→6 · meta 40 · gap ~$550–605M · semáforo amarillo",
};

export const FUNNEL_EJEMPLO = [
  { etapa: "Contactos", valor: 420, conv: null as string | null },
  { etapa: "Interés", valor: 126, conv: "30%" },
  { etapa: "Agendadas", valor: 48, conv: "38%" },
  { etapa: "Visitaron", valor: 36, conv: "75%" },
  { etapa: "Apps iniciadas", valor: 22, conv: "61%" },
  { etapa: "Apps enviadas", valor: 14, conv: "64%" },
  { etapa: "Matrículas", valor: 6, conv: "meta 40" },
];
